# Generated by Django 3.1.3 on 2020-12-01 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='new_linl',
            new_name='new_link',
        ),
    ]
